name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++ libxi-dev libgl-dev libxcursor-dev libxrandr-dev libxinerama-dev
    - name: configure
      run: ./premake5 gmake2 
    - name: make 
      run: make config=dist
    - name: Upload assets to a Release
      uses: AButler/upload-release-assets@v2.0.2
      with:
          files: 'Binaries/*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
