name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++ libxi-dev libgl-dev libxcursor-dev libxrandr-dev libxinerama-dev
    - name: configure
      run: ./premake5 gmake2 
    - name: make 
      run: make config=dist
    - run: |
        git config --global user.name 'Github Workflow'
        git config --global user.email 'fanis.deligiannis@gmail.com'
        git add -A
        git commit -am "Automated binaries build."
        git push
